In [144]:
import nltk


In [145]:
from nltk.corpus import brown

In [204]:
import sklearn

In [147]:
from sklearn.datasets import fetch_20newsgroups

In [148]:
newsgroups=fetch_20newsgroups()

In [319]:
X=newsgroups.data
Y=newsgroups.target_names

In [320]:
Y

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [636]:
A=newsgroups.target
A

array([7, 4, 4, ..., 3, 1, 8])

In [322]:
C.clear()

In [323]:
C=[]

In [324]:
for i in range(A.shape[0]):
    val={Y[A[i]]:X[i]}
    C.update(val)

AttributeError: 'list' object has no attribute 'update'

In [325]:
for i in range(A.shape[0]):
    C.append(Y[A[i]])
    

In [569]:
L=[]

In [570]:
D={}

In [633]:
final_list=[]
for i in range(len(Y)):
    List=[]
    List.append(Y[i])
    for j in range(len(C)):
        if(Y[i]==C[j]):
            List.append(X[j])
    final_list.append(List)
print(len(final_list[0]))
                
        

481


In [634]:
from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.tokenize import RegexpTokenizer
reg_exp="[a-zA-Z]+"
tokenizer=RegexpTokenizer(reg_exp)
from nltk.corpus import stopwords
stop=set(stopwords.words('english'))
from nltk.stem.snowball import SnowballStemmer, PorterStemmer
from nltk.stem.lancaster import LancasterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
ss = SnowballStemmer(language='english')
ps=PorterStemmer()

In [635]:

def remove_stopwords(sent,stopwords):
    useful_words = [w for w in sent if w not in stopwords]
    return useful_words


0

In [618]:
#Dataset Preparation

In [619]:
f_name=final_list[0][0]
for j in range(len(final_list[0])):
        final_array=[]
        text=final_list[0][j]
        text=tokenizer.tokenize(text)
        text=remove_stopwords(text,stop)
        new_text=[]
        for i in range(len(text)):
            new_text.append(ps.stem(text[i]))
        tf = TfidfVectorizer()
        vd = tf.fit_transform(new_text).toarray()
        final_array.append(vd)
D.update({f_name:final_array})

    
    

In [630]:
A=D.get('alt.atheism')

IndexError: list index out of range

In [585]:
final_list[3].remove(final_list[3][0])

In [483]:
final_list[3][0]

'comp.sys.ibm.pc.hardware'

In [ ]:
for i in range(final_list)

In [417]:
def remove_stopwords(sent,stopwords):
    useful_words = [w for w in sent if w not in stopwords]
    return useful_words

In [418]:
text=tokenizer.tokenize(text)
text=remove_stopwords(text,stop)


In [423]:
new_text=[]
for i in range(len(text)):
    new_text.append(ps.stem(text[i]))

In [425]:
len(new_text)

123

In [427]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
vd = tf.fit_transform(new_text).toarray()
print(np.argmax(vd[0]))

31


In [432]:
vd.shape

(123, 100)

In [430]:
tf.vocabulary_

{'afford': 0,
 'after': 1,
 'agre': 2,
 'allow': 3,
 'almost': 4,
 'and': 5,
 'atheist': 6,
 'cambridg': 7,
 'camp': 8,
 'caus': 9,
 'citizen': 10,
 'co': 11,
 'concentr': 12,
 'consid': 13,
 'constitut': 14,
 'consult': 15,
 'cwru': 16,
 'death': 17,
 'devast': 18,
 'die': 19,
 'diseas': 20,
 'don': 21,
 'doubt': 22,
 'dreamt': 23,
 'edu': 24,
 'ethnic': 25,
 'extermin': 26,
 'fair': 27,
 'far': 28,
 'final': 29,
 'form': 30,
 'from': 31,
 'gass': 32,
 'gener': 33,
 'goer': 34,
 'group': 35,
 'guess': 36,
 'happen': 37,
 'histori': 38,
 'holocost': 39,
 'if': 40,
 'ii': 41,
 'immedi': 42,
 'imprison': 43,
 'insert': 44,
 'intend': 45,
 'japanes': 46,
 'jew': 47,
 'keith': 48,
 'kill': 49,
 'kmr': 50,
 'let': 51,
 'line': 52,
 'look': 53,
 'malnutrit': 54,
 'manti': 55,
 'mathew': 56,
 'method': 57,
 'minor': 58,
 'mutil': 59,
 'nazi': 60,
 'newsread': 61,
 'organ': 62,
 'origin': 63,
 'painless': 64,
 'partli': 65,
 'peopl': 66,
 'po': 67,
 'polit': 68,
 'prepar': 69,
 'punish': 70,
 

In [289]:
for i in range()sents=sent_tokenize()

'From: mathew <mathew@mantis.co.uk>\nSubject: Re: <Political Atheists?\nOrganization: Mantis Consultants, Cambridge. UK.\nX-Newsreader: rusnews v1.01\nLines: 22\n\nkmr4@po.CWRU.edu (Keith M. Ryan) writes:\n> ( I am almost sure that Zyklon-B is immediate and painless method of \n> death. If not, insert soem other form. )\n> \n>         And, ethnic and minority groups have been killed, mutilated and \n> exterminated through out history, so I guess it was not unusual.\n> \n>         So, you would agree that the holocost would be allowed under the US \n> Constitution?  [ in so far, the punishment. I doubt they recieved what would \n> be considered a "fair" trial by US standards.\n\nDon\'t be so sure.  Look what happened to Japanese citizens in the US during\nWorld War II.  If you\'re prepared to say "Let\'s round these people up and\nstick them in a concentration camp without trial", it\'s only a short step to\ngassing them without trial.  After all, it seems that the Nazis originally\nonl

In [299]:
len(D.get('comp.graphics'))

11314

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),
 array([480, 584, 591, 590, 578, 593, 585, 594, 598, 597, 600, 595, 591,
        594, 593, 599, 546, 564, 465, 377]))

In [358]:
len(final_list[0])

11334

In [364]:
len(final_list[])

466

dict_keys(['rec.autos', 'comp.sys.mac.hardware', 'comp.graphics', 'sci.space', 'talk.politics.guns', 'sci.med', 'comp.sys.ibm.pc.hardware', 'comp.os.ms-windows.misc', 'rec.motorcycles', 'talk.religion.misc', 'misc.forsale', 'alt.atheism', 'sci.electronics', 'comp.windows.x', 'rec.sport.hockey', 'rec.sport.baseball', 'soc.religion.christian', 'talk.politics.mideast', 'talk.politics.misc', 'sci.crypt'])

(11314,)