In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [103]:
X=pd.read_csv('./Training/Logistic_X_Train.csv').values
Y=pd.read_csv('./Training/Logistic_Y_Train.csv').values
X_Test=pd.read_csv('./Testing/Logistic_X_Test.csv').values


In [104]:
#X=X[:100]
#Y=Y[:100]

In [105]:
def distance(p1,p2):
    return (np.sum((p1-p2)**2))**0.5

In [106]:
dist=[]
def KNN(X,Y,test,k=5):
    dist=[]
    for i in range(X.shape[0]):
        val=distance(X,test)
        dist.append((val,Y[i]))
    dist=np.array(sorted(dist))
    dist[:k]
    t=np.unique(dist,return_counts=True)
    t1=t[0][:2]
    t2=t[1][:2]
    a=np.argmax(t2)
    b=t1[a]
    return b
    

In [116]:
X_Test

array([[-0.76750773, -0.2618595 , -2.51483147],
       [-1.24165258,  1.44900144, -0.4130893 ],
       [ 1.92527007,  1.93176097,  1.34261917],
       ...,
       [-1.18696873,  0.94734729, -0.78638597],
       [-0.53232395,  1.84516978, -0.9935503 ],
       [ 0.54023217,  0.58099406,  0.38664901]])

In [107]:
Pred=[]
for i in range(X_Test.shape[0]):
    A=KNN(X,Y,X_Test[i])
    Pred.append(A)

(array([  0.       ,   1.       , 197.1375859]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 136.91072038]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 178.00261841]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 137.55638555]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 141.95267946]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 193.24407353]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 169.99587697]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 139.95049264]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 194.65655081]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 147.69841434]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 151.81448906]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 151.12181693]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 175.60956506]), arr

(array([  0.        ,   1.        , 136.46075441]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 147.17412801]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 183.14667885]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 155.02376214]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 232.06064769]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 133.07218803]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 141.72021228]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 139.32389106]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 137.00729217]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 194.07952751]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 160.83141385]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 130.45809714]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 137.81452579]), 

(array([  0.        ,   1.        , 127.65964098]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 129.84311851]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 140.37193166]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 159.76795625]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 162.96384822]), array([1509, 1491, 3000]))
(array([  0.       ,   1.       , 259.9797754]), array([1509, 1491, 3000]))
(array([  0.       ,   1.       , 140.4887431]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 134.93248497]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 178.89884228]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 153.08528135]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 157.68566437]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 141.76737883]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 138.59771949]), array(

(array([  0.        ,   1.        , 164.63999975]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 159.67259204]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 145.10577974]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 141.22887651]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 137.64219527]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 150.92508631]), array([1509, 1491, 3000]))
(array([  0.       ,   1.       , 135.9862615]), array([1509, 1491, 3000]))
(array([  0.       ,   1.       , 174.4406552]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 151.95549367]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 146.51164762]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 145.37664182]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 122.98513695]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 171.01635007]), array(

(array([  0.        ,   1.        , 127.77206557]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 133.70283385]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 167.73189572]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 142.70911785]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 208.75686258]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 195.99324696]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 211.49314598]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 142.18208869]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 140.99977881]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 154.39445421]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 208.13971802]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 177.71133845]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 159.17297093]), 

(array([  0.        ,   1.        , 156.35120505]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 166.85627005]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 121.89431546]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 166.71238697]), array([1509, 1491, 3000]))
(array([  0.       ,   1.       , 128.9839863]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 141.48338134]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 181.75695366]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 128.68587469]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 162.32536637]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 135.74670122]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 130.95533616]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 142.38123446]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 146.55527179]), arr

(array([  0.        ,   1.        , 215.02721256]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 136.18249612]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 193.09939215]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 124.52643236]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 153.39937877]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 158.68211677]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 233.78630215]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 180.23439607]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 133.05685358]), array([1509, 1491, 3000]))
(array([  0.       ,   1.       , 223.1139912]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 150.61099083]), array([1509, 1491, 3000]))
(array([  0.       ,   1.       , 126.1366972]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 183.02092072]), array(

(array([  0.        ,   1.        , 140.09414169]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 157.03731793]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 206.49180297]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 143.79580101]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 169.04499757]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 150.29771898]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 153.43779725]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 168.58953575]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 140.47964465]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 145.35445679]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 141.20125276]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 162.23635532]), array([1509, 1491, 3000]))
(array([  0.       ,   1.       , 189.5553833]), arr

(array([  0.        ,   1.        , 116.22981105]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 147.49885191]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 153.61215705]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 129.62512721]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 166.13595351]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 132.13404228]), array([1509, 1491, 3000]))
(array([  0.       ,   1.       , 199.1148333]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 128.59282009]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 233.84233778]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 152.49753675]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 162.82547303]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 174.54305224]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 157.62966932]), arr

(array([  0.        ,   1.        , 224.72080334]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 175.11454275]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 167.09350903]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 211.99735071]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 131.24335291]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 152.59247738]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 124.15975797]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 130.13427606]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 157.35319933]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 132.67535219]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 185.12418252]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 142.68674872]), array([1509, 1491, 3000]))
(array([  0.        ,   1.        , 146.70126728]), 

In [113]:
import csv
with open('./mycsv_Chemicals.csv','w',newline='')as f:
    fieldnames=['label']
    a=csv.DictWriter(f,fieldnames=fieldnames)
    a.writeheader()
    for i in range(Pred.shape[0]):
        a.writerow({'label':Pred[i]})

In [109]:
Pred=np.array(Pred)

In [110]:
Pred.shape

(1000,)

In [51]:
X[1]

array([-1.03607028,  0.80143631, -1.28371152])

In [115]:
Pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.